### ISSUE TITLE
Globally enable authentication, and disable for certain Routes/WebService

### ISSUE THREAD

**Issue by stuart-warren** [emicklei/go-restful#208]
Hi, love the framework.

I was trying to work out the best way to enable authentication globally, but disable it for certain Routes (rather than the reverse).
Is there a more sane way to have a Container filter execute after the Route filters than the below

``` go
// Container level
func auth_filter_enable(req *restful.Request, resp *restful.Response, chain *restful.FilterChain) {
	req.SetAttribute("shouldAuthenticate", true)
	chain.ProcessFilter(req, resp)
}

// Webservice or Route level
func auth_filter_disable(req *restful.Request, resp *restful.Response, chain *restful.FilterChain) {
	req.SetAttribute("shouldAuthenticate", false)
	chain.ProcessFilter(req, resp)
}

// Container level
func auth_filter(req *restful.Request, resp *restful.Response, chain *restful.FilterChain) {
	if len(chain.Filters) != chain.Index {
		// if not the last filter in the chain, append itself to the list
		chain.Filters = append(chain.Filters, chain.Filters[chain.Index-1])
	} else {
		// if last filter, authenticate!
		if req.Attribute("shouldAuthenticate").(bool) {
			log.Println("authenticate")
		}
	}
	chain.ProcessFilter(req, resp)
}

```

**Comment by emicklei** [comment]
It took me some time to understand this; in particular why and how the chain is being changed (getting a duplicate slot) while visiting its filters. I guess this is done because you do not control where filters are added and at what level.

At this moment, I cannot think of a better way to achieve this goal. As for this solution, won't the chain grow on each request? maybe replace the fitler slot with a passthrough function?

**Comment by emicklei** [comment]
The chain won't grow because its Filters is created on each Http request.

**Comment by stuart-warren** [comment]
Yeah, I just double checked that myself :)
