### ISSUE TITLE
How to specify an array Parameter

### ISSUE THREAD

**Issue by nikhiljindal** [emicklei/go-restful#225]
I want to specify the type of a parameter as an array of strings:

```
"type": "array",
      "items": {
       "type": "string"
      },
```

How do I tell go-restful this?
I can set Parameter.DataType("array"), but how do I specify the items type?
https://github.com/emicklei/go-restful/blob/38ef083f21a682a2c4dc3456646c0045d60fb2ce/parameter.go#L92

**Comment by emicklei** [comment]
Is this a non-body type?  I ask this because for request or response bodies, the Reads and Writes functions allow you to set the type implicitly.  If you inspect the JSON returned from the service, the models section will show the identifiers of all types used.

I will try to compose an example for your use case.

**Comment by nikhiljindal** [comment]
Yes. It is non-body type param (a query param, actually)

**Comment by emicklei** [comment]
Did you try using "array[string]"?   This notation is used for body parameters if specified using Reads or Writes such as Writes([]string{}).

**Comment by nikhiljindal** [comment]
Yes I tried that. It results in
```
"type": "array[string]"
```
While I want:
```
"type": "array",
      "items": {
       "type": "string"
      },
```

FWIW, I also tried "[]string" and it resulted in "type": "[]string" as well.

**Comment by emicklei** [comment]
i am thinking about adding the function DataTypeFrom(v interface{}) that will construct and reference a model.
