### ISSUE TITLE
There should be a way to send a custom HTTP status code with WriteEntity()

### ISSUE THREAD

**Issue by chrissnell** [emicklei/go-restful#229]
I would like my app to return error strings formatted as JSON (or XML, etc.) when an error is encountered.  I could use WriteServiceError() but it forces me to use go-restful's ServiceError struct which is rather opinionated.  I prefer to implement a generic error handling function that returns errors with a supplied HTTP status code and takes advantage of WriteEntity's auto-detection of the consumer's encoding preference.

I tried doing a WriteHeader() and then a WriteEntity() but this results in a bunch of log noise:

```
2015/09/10 12:13:37 http: multiple response.WriteHeader calls
```

I think it would be useful to have a WriteEntityWithReponseCode() or perhaps a WriteServiceErrorEntity() that let me pass an entity and a response code.  

How do you feel about this?

**Comment by emicklei** [comment]
Thank you for reporting this.

There has been a few other issues with WriteHeader and WriteEntity and the experience that it is not clear what happens. The fact that currently WriteEntity may write a header itself (406) and WriteHeader not always writes, contribute to that.

The http pkg documentation says:
```If WriteHeader has not yet been called, Write calls WriteHeader(http.StatusOK) before writing the data.```

So what is happening now with WriteHeader is that it delays the actual writing of the header until WriteEntity says the resource can be represented in the MIME type according to the Accept header.
And if you look at the WriteHeader implementation of Response, you can see all kinds of exceptions to his because for some codes there won't be anything to write. However, this is an assumption and causes problems such as the ```mulitple calls```.  E.g. writing a 404 and the string "404: NOT FOUND".

You are suggesting to add other methods with clear behavior. I favor that approach versus changing the current behavior (don't like to break api)  To decide what additions we need, the upcoming pluggable entityRW must also fit here. 

One other alternative is to make WriteHeader do what is says (without the exceptions) and also store the statuscode (for those that want to report in a filter). The WriteEntity will never write a statuscode and a solution must be found to detect a 406, e.g. adding a function IsAcceptable() bool.

Let me think about this issue a bit more.

**Comment by chrissnell** [comment]
Thanks.   Implementing a WriteEntityWithReponseCode isn't going to be easy--from my quick review of the code, it looks like the header is getting written all the way down in WriteJson() and WriteAsXML().  I would have to reimplement those functions, which is not ideal.   

Perhaps a better approach might be to change WriteHeader to always write the header and move the 2xx/3xx logic out to WriteEntity.   The Response struct could be changed so that statusCode becomes an exported struct member; codes could be set in the object and then WriteHeader could be called by WriteEntity/whatever as appropriate:

```
resp.StatusCode = http.StatusNotImplemented
resp.WriteEntity(&myStruct)
```

**Comment by emicklei** [comment]
Please have a look at the entityplug branch in which I changed the WriteHeader and WriteEntity as discussed.

**Comment by emicklei** [comment]
The recent merge of the entityplug branch offer the solution discussed.  The status code is written upon WriteHeader.

**Comment by chrissnell** [comment]
Thanks Ernest!  I will give it a shot now.
