### ISSUE TITLE
Multiple set header calls warnings

### ISSUE THREAD

**Issue by dahankzter** [emicklei/go-restful#28]
I get warnings from the standard library I guess about multiple calls to WriteHeader

2013/07/10 14:03:05 http: multiple response.WriteHeader calls

I think it is because go-restful detects mismatching content types and emits status code 406 (or some other in other cases) but still invokes the service method.

Isn't the idea to abort the call chain in case of an error?

**Comment by corvinusy** [comment]
this happens if someone calling sequentally: 

`response.WriteHeader(http.StatusCreated) // or any other http.Status`
`response.WriteEntity(yourEntity)`

response.WriteEntity function in its turn calls response.WriteHeader too. And this causes 'multiple response.WriteHeader calls'

As a workaround I use direct call 
`    response.WriteHeaderAndEntity(http.StatusCreated, yourEntity)`

**Comment by emicklei** [comment]
The WriteHeader has been changed recently for this reason. I believe it is now well documented what happens write each of the Write methods.

**Comment by sapamja** [comment]
I am still getting the same error.

**Comment by emicklei** [comment]
```WriteHeaderAndEntity``` is not a workaround, it is the right way to do it.
