### ISSUE TITLE
How to set port number

### ISSUE THREAD

**Issue by by2181** [emicklei/go-restful#351]
Examples have port 8080 as the default port, but is there a way to set it either in the app.yaml or using a container/webservice function?

**Comment by emicklei** [comment]
setting the listener port is outside the scope of this package. You can use the standard http.ListenAndServe function to specify the port. Because you mention app.yaml, I assume you are talking about AppEngine deployment. I believe such apps are available on port 80 and I do not know if that can be changed (or whether you could add a listener on a different port)
