### ISSUE TITLE
 Should go-restful's NewResponse method be initializingResponse.statusCode to StatusOK?

### ISSUE THREAD

**Issue by jlamillan** [emicklei/go-restful#388]
Is there a legitimize reason why `NewResponse` is [initializing Response.statusCode](https://github.com/emicklei/go-restful/blob/master/response.go#L36) to `http.StatusOK` instead of something like `0`?

Personally, I find this a counter intuitive at best, and misleading and confusing at worst. It seems to make debugging broken (or empty) HTTP responses from servers using this function more difficult.

**Comment by emicklei** [comment]
Good question. I understand what you mean.
I cannot recall a specific reason to initialise it.

Maybe I did so because, http.ResponseWriter.WriteHeader mentions:

```... If WriteHeader is not called explicitly, the first call to Write will trigger an implicit WriteHeader(http.StatusOK)....```

At this point, the only reason not to change the current NewResponse is when it will cause a breaking change to users of this package. I will have a closer look
