### ISSUE TITLE
How to reset the default container

### ISSUE THREAD

**Issue by balloman** [emicklei/go-restful#509]
I'm trying to write tests for some route functions, and need to test the usage of path paremeters. To do this, I'm using the default service container to serve the http requests. This works fine, but as soon as I want to run another request, then I get this error `WebService with duplicate root path detected` 

I tried removing the web service with restful.DefaultContainer.Remove(), but then I get this error: `cannot remove a WebService from a Container using the DefaultServeMux`

How on earth do I reset the default container so I can test routes multiple times?

**Comment by emicklei** [comment]
Hi,

One option is create a new container instead of using the default ; it will have its own ServeMux.
See https://github.com/emicklei/go-restful/blob/v3/examples/multi-container/restful-multi-containers.go

Replacing the `DefaultServeMux` in http does not work (there is a package private var referring to it).
